routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::post('paypal_status','OrderController@paypalStatus');
Route::get('paypal_invoice/{id}' , 'OrderController@paypalInvoice');


Route::get('register/verify/{token}', 'Auth\RegisterController@verify');

Route::get('/getrate/{service_id}/{urgency_id}', 'RateController@getrate');
Route::get('/faq' , 'HomeController@faq');
Route::get('/email','HomeController@email');

Route::group(['middleware' => ['web', 'auth']], function () {

	Route::get('/home', 'HomeController@index');
	Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
	Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

	Route::get('/user/{id}','HomeController@userprofile'); 	
	Route::get('/placeorder', 'OrderController@placeorder');
	
	Route::post('imageUploadForm', 'HomeController@upload_photo' )->name('users.uploadpic');

	Route::get('/active', 'OrderController@active');
	Route::get('/completed', 'OrderController@completed');
	Route::get('/revision', 'OrderController@revision'); 
	Route::get('/shoppingcart', 'OrderController@shoppingcart');
	Route::get('/payment', 'OrderController@payment');

	Route::get('/dashboard-writer', 'HomeController@writer');

	Route::get('/changetopaid/{id}', 'OrderController@changetopaid')->name('orders.changetopaid');
	Route::get('/vieworder/{id}', 'OrderController@vieworder')->name('orders.vieworder');
	Route::get('/uploaddoc/{id}', 'OrderController@uploaddoc')->name('orders.uploaddoc');
	Route::get('/payorder/{id}', 'OrderController@payorder')->name('orders.payorder');
	Route::get('/cancel/{id}','OrderController@cancelorder')->name('orders.cancelorder');
	Route::post('/messeges/upload', 'MessageController@upload')->name('messages.upload');
	Route::get('/orders/{id}/download' , 'OrderController@download') ->name('orders.downloads');
	Route::get('/orders/{id}/in_revision' , 'OrderController@in_revision') ->name('orders.in_revision');
	Route::get('/orders/{id}/complete' , 'OrderController@complete') ->name('orders.complete');
	Route::resource("orders","OrderController");

	Route::get('/ordersstatus/{id}', 'OrderController@status');
	Route::get('/ordersstatus/', 'OrderController@searchstatus');

	//writers
	Route::get('/job/active' , 'WriterController@active'); 
	Route::get('/job/pending' , 'WriterController@pendingjob'); 
	Route::get('/job/completed' , 'WriterController@completed'); 
	Route::get('/job/revision' , 'WriterController@revision'); 
	Route::get('/writer/messages' , 'MessageController@writer'); 
	Route::get('/job' , 'WriterController@writer_view'); 
	
	Route::post('/job/uploaddoc' , 'WriterController@upload_final_doc') ->name('writers.upload_doc');
	Route::get('/job/{id}', 'WriterController@vieworder')->name('writers.vieworder');
	Route::get('/job/{id}/apply', 'WriterController@applyjob')->name('writers.applyjob');

	Route::get('/orders/message/{id}','MessageController@read')->name('messages.read');

});

Route::group(['middleware' => ['App\Http\Middleware\admin' ]] , function () {

	Route::get('/dashboard-admin', 'HomeController@admin');

	Route::resource("services","ServiceController");
	Route::resource("urgencies","UrgencyController");
	Route::resource("levels","LevelController");
	Route::resource("spacings","SpacingController");
	Route::resource("pages","PageController");
	Route::resource("citations","CitationController");
	Route::resource("sources","SourceController");
	Route::resource("statuses","StatusController");
	Route::resource("rates","RateController");
	Route::resource("messages","MessageController");


	//admin
	Route::get('/users' , 'HomeController@user');
  	Route::get('/users_download','HomeController@users_download');
  	Route::get('/users/filterby' , 'HomeController@filterby') ->name('admins.searchrole'); 
  	Route::get('/users/searchname' , 'HomeController@searchname') ->name('admins.searchname'); 
	Route::get('/users/{id}/{type?}' , 'HomeController@change_user') ->name('admins.change_user');

	//export 
	Route::get('/export','OrderController@export');
	
	Route::get('/messages/{id}/approve_message' , 'MessageController@approve') ->name('messages.approve');
	Route::get('/messages/{id}/decline_message' , 'MessageController@decline') ->name('messages.decline');

	Route::get('/add_writer' , 'WriterController@registerform');
	Route::post('/register_writer' , 'WriterController@register_writer');
	
	Route::get('/orders/approve/{id}/{writer_id}' , 'WriterController@approvejob') ->name('orders.approvejob');
	Route::get('/orders/decline/{id}/{writer_id}' , 'WriterController@decline') ->name('orders.decline');

	Route::get('/orders/{id}/cancel_writer' , 'OrderController@cancel_writer') ->name('orders.cancel_writer');
	Route::get('/orders/{id}/assign_writer' , 'OrderController@assign_writer') ->name('orders.assign_writer'); 
	Route::get('/orders/{id}/approve_doc' , 'OrderController@approve_doc') ->name('orders.approve_doc');
	Route::get('/orders/{id}/reject_doc' , 'OrderController@reject_doc') ->name('orders.reject_doc');
	Route::get('/orders/approve/{id}/{writer_id}' , 'WriterController@approvejob') ->name('orders.approvejob');
	Route::get('/orders/decline/{id}/{writer_id}' , 'WriterController@decline') ->name('orders.decline');

});

resources/views/pages/create.blade.php
@extends('layouts.admin')

@section('subcontent')

  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">

    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Pages / Create </h1>
    </div>


    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('pages.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('page')) has-error @endif">
                       <label for="page-field">Page</label>
                    <input type="text" id="page-field" name="page" class="form-control" value="{{ old("page") }}"/>
                       @if($errors->has("page"))
                        <span class="help-block">{{ $errors->first("page") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('words')) has-error @endif">
                       <label for="words-field">Words</label>
                    <input type="text" id="words-field" name="words" class="form-control" value="{{ old("words") }}"/>
                       @if($errors->has("words"))
                        <span class="help-block">{{ $errors->first("words") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('description')) has-error @endif">
                       <label for="description-field">Description</label>
                    <textarea class="form-control" id="description-field" rows="3" name="description">{{ old("description") }}</textarea>
                       @if($errors->has("description"))
                        <span class="help-block">{{ $errors->first("description") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('value')) has-error @endif">
                       <label for="value-field">Value</label>
                    <input type="text" id="value-field" name="value" class="form-control" value="{{ old("value") }}"/>
                       @if($errors->has("value"))
                        <span class="help-block">{{ $errors->first("value") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('pages.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  
$("#nav-others").addClass("active");
</script>
@endsection

resources/views/pages/edit.blade.php
@extends('layouts.admin')

@section('subcontent')

  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">

    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Pages / Edit #{{$page->id}}</h1>
    </div>


    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('pages.update', $page->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('page')) has-error @endif">
                       <label for="page-field">Page</label>
                    <input type="text" id="page-field" name="page" class="form-control" value="{{ is_null(old("page")) ? $page->page : old("page") }}"/>
                       @if($errors->has("page"))
                        <span class="help-block">{{ $errors->first("page") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('words')) has-error @endif">
                       <label for="words-field">Words</label>
                    <input type="text" id="words-field" name="words" class="form-control" value="{{ is_null(old("words")) ? $page->words : old("words") }}"/>
                       @if($errors->has("words"))
                        <span class="help-block">{{ $errors->first("words") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('description')) has-error @endif">
                       <label for="description-field">Description</label>
                    <textarea class="form-control" id="description-field" rows="3" name="description">{{ is_null(old("description")) ? $page->description : old("description") }}</textarea>
                       @if($errors->has("description"))
                        <span class="help-block">{{ $errors->first("description") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('value')) has-error @endif">
                       <label for="value-field">Value</label>
                    <input type="text" id="value-field" name="value" class="form-control" value="{{ is_null(old("value")) ? $page->value : old("value") }}"/>
                       @if($errors->has("value"))
                        <span class="help-block">{{ $errors->first("value") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('pages.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
 
$("#nav-others").addClass("active");
</script>
@endsection

resources/views/pages/index.blade.php
@extends('layouts.admin')

@section('subcontent')
<div class="row">
    <div class="col-xs-12">
    <div class="col-xs-12" style="margin-top:15px">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="pull-left">Pages</h3>
        </div>
        <div class="box-body">


            @if($pages->count())
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>PAGE</th>
                        <th>WORDS</th>
                        <th>DESCRIPTION</th>
                        <th>VALUE</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($pages as $page)
                            <tr>
                                <td>{{$page->id}}</td>
                                <td>{{$page->page}}</td>
                    <td>{{$page->words}}</td>
                    <td>{{$page->description}}</td>
                    <td>{{$page->value}}</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('pages.show', $page->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                    <a class="btn btn-xs btn-warning" href="{{ route('pages.edit', $page->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('pages.destroy', $page->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $pages->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>
</div>
</div>
</div>
@endsection

@section('scripts')
<script type="text/javascript">
$("#nav-others").addClass("active");
</script>
@endsection

resources/views/pages/show.blade.php
@extends('layouts.admin')

@section('subcontent')

<div class="page-header">
        <h1>Pages / Show #{{$page->id}}</h1>
        <form action="{{ route('pages.destroy', $page->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('pages.edit', $page->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>

    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="page">PAGE</label>
                     <p class="form-control-static">{{$page->page}}</p>
                </div>
                    <div class="form-group">
                     <label for="words">WORDS</label>
                     <p class="form-control-static">{{$page->words}}</p>
                </div>
                    <div class="form-group">
                     <label for="description">DESCRIPTION</label>
                     <p class="form-control-static">{{$page->description}}</p>
                </div>
                    <div class="form-group">
                     <label for="value">VALUE</label>
                     <p class="form-control-static">{{$page->value}}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('pages.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection

@section('scripts')
<script type="text/javascript">
$("#nav-others").addClass("active");
</script>
@endsection