routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::post('paypal_status','OrderController@paypalStatus');
Route::get('paypal_invoice/{id}' , 'OrderController@paypalInvoice');


Route::get('register/verify/{token}', 'Auth\RegisterController@verify');

Route::get('/getrate/{service_id}/{urgency_id}', 'RateController@getrate');
Route::get('/faq' , 'HomeController@faq');
Route::get('/email','HomeController@email');

Route::group(['middleware' => ['web', 'auth']], function () {

	Route::get('/home', 'HomeController@index');
	Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
	Route::post('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

	Route::get('/user/{id}','HomeController@userprofile'); 	
	Route::get('/placeorder', 'OrderController@placeorder');
	
	Route::post('imageUploadForm', 'HomeController@upload_photo' )->name('users.uploadpic');

	Route::get('/active', 'OrderController@active');
	Route::get('/completed', 'OrderController@completed');
	Route::get('/revision', 'OrderController@revision'); 
	Route::get('/shoppingcart', 'OrderController@shoppingcart');
	Route::get('/payment', 'OrderController@payment');

	Route::get('/dashboard-writer', 'HomeController@writer');

	Route::get('/changetopaid/{id}', 'OrderController@changetopaid')->name('orders.changetopaid');
	Route::get('/vieworder/{id}', 'OrderController@vieworder')->name('orders.vieworder');
	Route::get('/uploaddoc/{id}', 'OrderController@uploaddoc')->name('orders.uploaddoc');
	Route::get('/payorder/{id}', 'OrderController@payorder')->name('orders.payorder');
	Route::get('/cancel/{id}','OrderController@cancelorder')->name('orders.cancelorder');
	Route::post('/messeges/upload', 'MessageController@upload')->name('messages.upload');
	Route::get('/orders/{id}/download' , 'OrderController@download') ->name('orders.downloads');
	Route::get('/orders/{id}/in_revision' , 'OrderController@in_revision') ->name('orders.in_revision');
	Route::get('/orders/{id}/complete' , 'OrderController@complete') ->name('orders.complete');
	Route::resource("orders","OrderController");

	Route::get('/ordersstatus/{id}', 'OrderController@status');
	Route::get('/ordersstatus/', 'OrderController@searchstatus');

	//writers
	Route::get('/job/active' , 'WriterController@active'); 
	Route::get('/job/pending' , 'WriterController@pendingjob'); 
	Route::get('/job/completed' , 'WriterController@completed'); 
	Route::get('/job/revision' , 'WriterController@revision'); 
	Route::get('/writer/messages' , 'MessageController@writer'); 
	Route::get('/job' , 'WriterController@writer_view'); 
	
	Route::post('/job/uploaddoc' , 'WriterController@upload_final_doc') ->name('writers.upload_doc');
	Route::get('/job/{id}', 'WriterController@vieworder')->name('writers.vieworder');
	Route::get('/job/{id}/apply', 'WriterController@applyjob')->name('writers.applyjob');

	Route::get('/orders/message/{id}','MessageController@read')->name('messages.read');

});

Route::group(['middleware' => ['App\Http\Middleware\admin' ]] , function () {

	Route::get('/dashboard-admin', 'HomeController@admin');

	Route::resource("services","ServiceController");
	Route::resource("urgencies","UrgencyController");
	Route::resource("levels","LevelController");
	Route::resource("spacings","SpacingController");
	Route::resource("pages","PageController");
	Route::resource("citations","CitationController");
	Route::resource("sources","SourceController");
	Route::resource("statuses","StatusController");
	Route::resource("rates","RateController");
	Route::resource("messages","MessageController");


	//admin
	Route::get('/users' , 'HomeController@user');
  	Route::get('/users_download','HomeController@users_download');
  	Route::get('/users/filterby' , 'HomeController@filterby') ->name('admins.searchrole'); 
  	Route::get('/users/searchname' , 'HomeController@searchname') ->name('admins.searchname'); 
	Route::get('/users/{id}/{type?}' , 'HomeController@change_user') ->name('admins.change_user');

	//export 
	Route::get('/export','OrderController@export');
	
	Route::get('/messages/{id}/approve_message' , 'MessageController@approve') ->name('messages.approve');
	Route::get('/messages/{id}/decline_message' , 'MessageController@decline') ->name('messages.decline');

	Route::get('/add_writer' , 'WriterController@registerform');
	Route::post('/register_writer' , 'WriterController@register_writer');
	
	Route::get('/orders/approve/{id}/{writer_id}' , 'WriterController@approvejob') ->name('orders.approvejob');
	Route::get('/orders/decline/{id}/{writer_id}' , 'WriterController@decline') ->name('orders.decline');

	Route::get('/orders/{id}/cancel_writer' , 'OrderController@cancel_writer') ->name('orders.cancel_writer');
	Route::get('/orders/{id}/assign_writer' , 'OrderController@assign_writer') ->name('orders.assign_writer'); 
	Route::get('/orders/{id}/approve_doc' , 'OrderController@approve_doc') ->name('orders.approve_doc');
	Route::get('/orders/{id}/reject_doc' , 'OrderController@reject_doc') ->name('orders.reject_doc');
	Route::get('/orders/approve/{id}/{writer_id}' , 'WriterController@approvejob') ->name('orders.approvejob');
	Route::get('/orders/decline/{id}/{writer_id}' , 'WriterController@decline') ->name('orders.decline');

});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    public function status(){
    	return $this->belongsTo(Status::class);
    }

    public function service(){
    	return $this->belongsTo(Service::class);
    }

    public function urgency(){
    	return $this->belongsTo(Urgency::class);
    }

    public function level(){
    	return $this->belongsTo(Level::class);
    }

    public function spacing(){
    	return $this->belongsTo(Spacing::class);
    }

    public function page(){
    	return $this->belongsTo(Page::class);
    }

    public function citation(){
    	return $this->belongsTo(Citation::class);
    }

    public function source(){
    	return $this->belongsTo(Source::class);
    }

    public function transactions()
    {
        return $this->hasMany(Transactions::class);
    }

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function writer(){
        return $this->belongsTo(User::class);
    }


}

app/Http/Controllers/OrderController.php
<?php 

namespace App\Http\Controllers;


use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\User;
use App\Order;
use App\Transactions ;
use Illuminate\Http\Request;
use Auth;
use DB ; 
use Carbon\Carbon;

use Config;
use PayPal\Rest\ApiContext;
use PayPal\Auth\OAuthTokenCredential;
use PayPal\Api\Address;
use PayPal\Api\BillingInfo;
use PayPal\Api\Cost;
use PayPal\Api\Currency;
use PayPal\Api\Invoice;
use PayPal\Api\InvoiceAddress;
use PayPal\Api\InvoiceItem;
use PayPal\Api\MerchantInfo;
use PayPal\Api\PaymentTerm;
use PayPal\Api\Phone;
use PayPal\Api\ShippingInfo;

class OrderController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	  private $_api_context;

	 public function __construct()
    {
        $this->middleware('auth');
        $paypal_conf = Config::get('paypal');
        $this->_api_context = new ApiContext(new OAuthTokenCredential($paypal_conf['client_id'], $paypal_conf['secret']));
        $this->_api_context->setConfig($paypal_conf['settings']);
    }


	public function index()
	{
		$orders = Order::orderBy('id', 'desc')->paginate(20);

		return view('orders.index', compact('orders'));
	}

	public function status($id){
		$search = $id ; 
		$orders = Order::where('status_id' , '=' , $id)->orderBy('id','desc')->paginate(20);

		return view('orders.index', compact('orders', 'search')); 

	}

	public function searchstatus (Request $request){
		
        $search = $request->status;
        if($search == 0 ){
        	$orders = Order::orderBy('id','desc')->paginate(20);
        }else{
        	$orders = Order::where('status_id', '=', $search)->orderBy('id', 'desc')->paginate(20);
         }
        return view('orders.index', compact('orders','search'))->renderSections()['subcontent'];
    
    }

	public function shoppingcart()
	{
		$orders=\App\Order::where('user_id','=',Auth::user()->id)
                ->where('status_id','=','4')
                ->orderBy('id', 'desc')->paginate(6);

        $status='unpaid';

		return view('orders.shoppingcart', compact('orders','status'));
	}

	public function active()
	{
		$orders=\App\Order::where('user_id','=',Auth::user()->id)
                ->where(function($query)
                        {
                            $query->where('status_id', '=', '1')
                                  ->orwhere('status_id', '=', '5')
                                  ->orwhere('status_id', '=', '6');
                            })
                ->orderBy('id', 'desc')->get();

        $status='active';

		return view('orders.orders', compact('orders','status'));
	}

	public function approve()
	{
		$orders=\App\Order::where('user_id','=',Auth::user()->id)
                ->where('status_id','=','4')
                ->orderBy('id', 'desc')->paginate(6);


		// return view('orders.active', compact('orders'));
	}

	public function revision()
	{
		$orders=\App\Order::where('user_id','=',Auth::user()->id)
                ->where('status_id','=','3')
                ->orderBy('id', 'desc')->paginate(6);

		$status='revision';

		return view('orders.orders', compact('orders','status'));
	}

	public function in_revision($id){
		$order = Order::findOrFail($id);
    	
    	$order->status_id = 3 ; 
    	$order->revision_count= $order->revision_count+1;
    	$order->save();

    	DB::table('active_orders')->where('order_id','=',$id)->where('status_id','=',1)->update(['status_id' => 3]);

    	return redirect('/vieworder/'.$id) ->with('message' , ' Order Being Revision');

    }

	public function completed()
	{
		$orders=\App\Order::where('user_id','=',Auth::user()->id)
                ->where('status_id','=','2')
                ->orderBy('id', 'desc')->paginate(6);

		$status='completed';

		return view('orders.orders', compact('orders','status'));
	}

	public function received()
	{
		$orders=\App\Order::where('user_id','=',Auth::user()->id)
                ->where('status_id','=','7')
                ->orderBy('id', 'desc')->paginate(6);


		// return view('orders.active', compact('orders'));
	}
	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('orders.create');
	}

	public function placeorder()
	{
		return view('orders.placeorder');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$order = new Order();

		$order->title = $request->input("title");
        $order->description = $request->input("description");
        
        if ($request->input("date")) {
        	$order->date = $request->input("date");
 		} else {
 			$order->date = date("Y-m-d");
 		}    

 		
       	$order->status_id = 4;
        

        $order->service_id = $request->input("service_id");

        $order->due_date = $request->input("due_date");
        $order->urgency_id = $request->input("urgency_id");

        if ($request->input("due_date")) {
        	$order->due_date = $request->input("due_date");
 		} else {
 			$urgency = \App\Urgency::where('id','=',$order->urgency_id)->first();
 			$date=strtotime(date('Y-m-d h:i:s')); 
 			$order->due_date = date('Y-m-d h:i:s',strtotime('+'.$urgency->value.' days',$date));
 		}
        
        $order->level_id = $request->input("level_id");
        $order->spacing_id = $request->input("spacing_id");
        $order->page_id = $request->input("page_id");
        $order->citation_id = $request->input("citation_id");
        $order->source_id = $request->input("source_id");

        $rate = \App\Rate::where('service_id','=',$order->service_id)
		 		->where('level_id','=',$order->level_id)
		 		->where('urgency_id','=',$order->urgency_id)
		 		->first();
        $order->priceperpage = $rate->rate;

        $spacing = \App\Spacing::where('id','=',$order->spacing_id)->first();
        $page = \App\Page::where('id','=',$order->page_id)->first();

        $order->totalprice = $order->priceperpage*$spacing->value*$page->value;

        if ($request->input("user_id")) {
        	$order->user_id = $request->input("user_id");
        } else {
        	$order->user_id = \Auth::user()->id;;
        }
		
		$order->save();

		return redirect('/uploaddoc/'.$order->id)->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$order = Order::findOrFail($id);

		return view('orders.show', compact('order'));
	}

	public function vieworder($id)
	{
		if(Auth::user()->user_type == 1){
			$thisorder = Order::findOrFail($id);

			if($thisorder->status_id == 5 || $thisorder->status_id == 6 || $thisorder->status_id == 1 ){
				$orders=\App\Order::where(function($query)
                        {
                            $query->where('status_id', '=', '1')
                                  ->orwhere('status_id', '=', '5')
                                  ->orwhere('status_id', '=', '6');
                            })->orderBy('id', 'desc')->get();

                $status='Active';	
            }else{
				$orders=\App\Order::where('status_id','=',$thisorder->status_id)->where('user_id','=', Auth::user()->id)->orderBy('id', 'desc')->paginate(6);
            }


           }elseif(Auth::user()->user_type == 2){
           		$thisorder = Order::findOrFail($id);
 				$orders = DB::table('active_orders')->where('status_id','=',$thisorder->status_id)->where('writer_id','=',Auth::user()->id)->orderBy('id','desc')->get();

           }elseif(Auth::user()->user_type == 3 ){
           		
           		$thisorder = Order::findOrFail($id);           	
           		$orders=\App\Order::where('status_id','=',$thisorder->status_id)->orderBy('id', 'desc')->get();

           }
		\Braintree_Configuration::environment(env('ENVIRONMENT'));
		\Braintree_Configuration::merchantId(env('MERCHANTID'));
		\Braintree_Configuration::publicKey(env('PUBLICKEY'));
		\Braintree_Configuration::privateKey(env('PRIVATEKEY'));	

		return view('orders.vieworder', compact('thisorder','orders' ,'status'));
	}


	public function payorder($id)
	{
		$order = Order::findOrFail($id);
		\Braintree_Configuration::environment('sandbox');
		\Braintree_Configuration::merchantId('hzkf5g6q3bv46yws');
		\Braintree_Configuration::publicKey('35g2qfy4pbhxqj8j');
		\Braintree_Configuration::privateKey('709a0a4eba94928888d84388dfc614be');		

		return view('orders.payorder', compact('order'));
	}

	public function uploaddoc($id)
	{
		$order = Order::findOrFail($id);

		return view('orders.uploaddoc', compact('order'));
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$order = Order::findOrFail($id);

		return view('orders.edit', compact('order'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$order = Order::findOrFail($id);

		$order->title = $request->input("title");
        $order->description = $request->input("description");
        $order->date = $request->input("date");
        $order->status_id = $request->input("status_id");
        $order->service_id = $request->input("service_id");
        $order->due_date = $request->input("due_date");
        $order->urgency_id = $request->input("urgency_id");
        $order->level_id = $request->input("level_id");
        $order->spacing_id = $request->input("spacing_id");
        $order->page_id = $request->input("page_id");
        $order->citation_id = $request->input("citation_id");
        $order->source_id = $request->input("source_id");

		$order->save();

		return redirect()->route('orders.index')->with('message', 'Order #'.$id.' updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */

resources/views/orders/active.blade.php
@extends('layouts.user')

@section('subcontent')


<div class="panel panel-default">
    <div class="panel-heading">Active Order</div>


    <div class="panel-body">
        <div class="row">
            <div class="col-xs-12">
                @if($orders->count())
                    @foreach($orders as $order)
                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <div class="panel panel-default panel-primary">
                          <div class="panel-heading"><p>{{$order->title}}</p></div>
                          <div class="panel-body">
                            <h6 class="text-right">Order #{{sprintf("%06s",$order->id)}}</h6>
                            <h5>{{$order->due_date}}</h5>
                            <p>{{$order->description}}</p>
                            <p>{{$order->service->title}}</p>
                            <p>{{$order->urgency->title}}</p>
                            <p>{{$order->level->title}}</p>
                            <p>{{$order->spacing->title}} Spacing</p>
                            <p>{{$order->page->value}} Pages</p>
                            <p>Created at {{$order->date}}</p>
                            <h5>$ {{$order->priceperpage}}</h5>
                            <h6>$ {{$order->totalprice}}</h6>
                            <a class="btn btn-xs btn-primary" href="{{ route('orders.vieworder', $order->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                          </div>
                        </div>
                        
                    </div>
                    @endforeach

                    {!! $orders->render() !!}
                @else
                    <h3 class="text-center alert alert-info">You have no active order.</h3>
                @endif

            </div>
        </div>
    </div>
</div>
        
@endsection

@section('scripts')
<script type="text/javascript">
$("#nav-active").addClass("active");
</script>
@endsection

resources/views/orders/create.blade.php
@extends('layouts.admin')

@section('subcontent')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.4/build/jquery.datetimepicker.min.css"/ >


    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Orders / Create </h1>
    </div>


    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('orders.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                <div class="form-group @if($errors->has('title')) has-error @endif">
                       <label for="title-field">Title</label>
                    <input type="text" id="title-field" name="title" class="form-control" value="{{ old("title") }}"/>
                       @if($errors->has("title"))
                        <span class="help-block">{{ $errors->first("title") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('description')) has-error @endif">
                       <label for="description-field">Description</label>
                    <textarea class="form-control" id="description-field" rows="3" name="description">{{ old("description") }}</textarea>
                       @if($errors->has("description"))
                        <span class="help-block">{{ $errors->first("description") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('date')) has-error @endif">
                       <label for="date-field">Date</label>
                    <input type="text" id="date-field" name="date" class="form-control date-picker" value="{{ old("date") }}"/>
                       @if($errors->has("date"))
                        <span class="help-block">{{ $errors->first("date") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('status_id')) has-error @endif">
                       <label for="status_id-field">Status</label>
                   
                    <select name="status_id" class="form-control">
                      @foreach(\App\Status::get() as $status)
                      <option value="{{$status->id}}" {{(old("status_id")==$status->id)? 'selected':''}} >{{$status->title}}</option>
                      @endforeach
                    </select>

                       @if($errors->has("status_id"))
                        <span class="help-block">{{ $errors->first("status_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('service_id')) has-error @endif">
                       <label for="service_id-field">Service</label>
                  

                    <select name="service_id" class="form-control">
                      @foreach(\App\Service::get() as $service)
                      <option value="{{$service->id}}" {{(old("service_id")==$service->id)? 'selected':''}} >{{$service->title}}</option>
                      @endforeach
                    </select>

                       @if($errors->has("service_id"))
                        <span class="help-block">{{ $errors->first("service_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('due_date')) has-error @endif">
                       <label for="due_date-field">Due_date</label>
                    <input type="text" id="due_date-field" name="due_date" class="form-control" value="{{ old("due_date") }}"/>
                       @if($errors->has("due_date"))
                        <span class="help-block">{{ $errors->first("due_date") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('urgency_id')) has-error @endif">
                       <label for="urgency_id-field">Urgency_id</label>
                

                    <select name="urgency_id" class="form-control">
                      @foreach(\App\Urgency::get() as $urgency)
                      <option value="{{$urgency->id}}" {{(old("urgency_id")==$urgency->id)? 'selected':''}} >{{$urgency->title}}</option>
                      @endforeach
                    </select>

                       @if($errors->has("urgency_id"))
                        <span class="help-block">{{ $errors->first("urgency_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('level_id')) has-error @endif">
                       <label for="level_id-field">Level_id</label>
                  
                      <select name="level_id" class="form-control">
                      @foreach(\App\Level::get() as $level)
                      <option value="{{$level->id}}" {{(old("level_id")==$level->id)? 'selected':''}} >{{$level->title}}</option>
                      @endforeach
                    </select>


                       @if($errors->has("level_id"))
                        <span class="help-block">{{ $errors->first("level_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('spacing_id')) has-error @endif">
                       <label for="spacing_id-field">Spacing_id</label>
                    
                    <select name="spacing_id" class="form-control">
                      @foreach(\App\Spacing::get() as $spacing)
                      <option value="{{$spacing->id}}" {{(old("spacing_id")==$spacing->id)? 'selected':''}} >{{$spacing->title}}</option>
                      @endforeach
                    </select>



                       @if($errors->has("spacing_id"))
                        <span class="help-block">{{ $errors->first("spacing_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('page_id')) has-error @endif">
                       <label for="page_id-field">Page_id</label>
                    
                    <select name="page_id" class="form-control">
                      @foreach(\App\Page::get() as $page)
                      <option value="{{$page->id}}" {{(old("page_id")==$page->id)? 'selected':''}} >{{$page->page}} Pages</option>
                      @endforeach
                    </select>


                       @if($errors->has("page_id"))
                        <span class="help-block">{{ $errors->first("page_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('citation_id')) has-error @endif">
                       <label for="citation_id-field">Citation_id</label>
                  

                    <select name="citation_id" class="form-control">
                      @foreach(\App\Citation::get() as $citation)
                      <option value="{{$citation->id}}" {{(old("citation_id")==$citation->id)? 'selected':''}} >{{$citation->title}}</option>
                      @endforeach
                    </select>


                       @if($errors->has("citation_id"))
                        <span class="help-block">{{ $errors->first("citation_id") }}</span>
                       @endif
                    </div>
                    <div class="form-group @if($errors->has('source_id')) has-error @endif">
                       <label for="source_id-field">Source_id</label>
                 

                    <select name="source_id" class="form-control">
                      @foreach(\App\Source::get() as $source)
                      <option value="{{$source->id}}" {{(old("source_id")==$source->id)? 'selected':''}} >{{$source->title}}</option>
                      @endforeach
                    </select>


                       @if($errors->has("source_id"))
                        <span class="help-block">{{ $errors->first("source_id") }}</span>
                       @endif
                    </div>
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('orders.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.4/build/jquery.datetimepicker.full.js"></script>
  <script>
    $('.date-picker').datepicker({
      format:'yyyy-mm-dd'
    });

    $('#due_date-field').datetimepicker({
      format:'Y-m-d H:i'
    });

  $("#nav-orders").addClass("active");
</script>
@endsection

resources/views/orders/show.blade.php
@extends('layouts.admin')

@section('subcontent')
<div class="page-header">
        <h1>Orders / Show #{{$order->id}}</h1>
        <form action="{{ route('orders.destroy', $order->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('orders.edit', $order->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>

    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="title">TITLE</label>
                     <p class="form-control-static">{{$order->title}}</p>
                </div>
                    <div class="form-group">
                     <label for="description">DESCRIPTION</label>
                     <p class="form-control-static">{{$order->description}}</p>
                </div>
                    <div class="form-group">
                     <label for="date">DATE</label>
                     <p class="form-control-static">{{$order->date}}</p>
                </div>
                    <div class="form-group">
                     <label for="status_id">STATUS_ID</label>
                     <p class="form-control-static">{{$order->status_id}}</p>
                </div>
                    <div class="form-group">
                     <label for="service_id">SERVICE_ID</label>
                     <p class="form-control-static">{{$order->service_id}}</p>
                </div>
                    <div class="form-group">
                     <label for="due_date">DUE_DATE</label>
                     <p class="form-control-static">{{$order->due_date}}</p>
                </div>
                    <div class="form-group">
                     <label for="urgency_id">URGENCY_ID</label>
                     <p class="form-control-static">{{$order->urgency_id}}</p>
                </div>
                    <div class="form-group">
                     <label for="level_id">LEVEL_ID</label>
                     <p class="form-control-static">{{$order->level_id}}</p>
                </div>
                    <div class="form-group">
                     <label for="spacing_id">SPACING_ID</label>
                     <p class="form-control-static">{{$order->spacing_id}}</p>
                </div>
                    <div class="form-group">
                     <label for="page_id">PAGE_ID</label>
                     <p class="form-control-static">{{$order->page_id}}</p>
                </div>
                    <div class="form-group">
                     <label for="citation_id">CITATION_ID</label>
                     <p class="form-control-static">{{$order->citation_id}}</p>
                </div>
                    <div class="form-group">
                     <label for="source_id">SOURCE_ID</label>
                     <p class="form-control-static">{{$order->source_id}}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('orders.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection
@section('scripts')
<script type="text/javascript">
$("#nav-orders").addClass("active");
</script>
@endsection